name: Build and Publish to Registry

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract tag without "v"
        run: echo "TAG_NAME=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Authenticate to GCP with OIDC
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ vars.WIP_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and tag Docker image
        run: |
          docker build -t us-docker.pkg.dev/koreo-dev/koreo/ui:latest -t us-docker.pkg.dev/koreo-dev/koreo/ui:$TAG_NAME .

      - name: Push image to Artifact Registry
        run: |
          docker push us-docker.pkg.dev/koreo-dev/koreo/ui:$TAG_NAME
          docker push us-docker.pkg.dev/koreo-dev/koreo/ui:latest
